def trollface():
    print("""
    AAAAAAAAAAAAAAAAAAP A  LAAAAAAA            JAAK   AAAA  FZAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAANA             IZNMONIN K XNU  HCKZ        OAAANAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAABAK    IAAAAADAA ZAZW   A A AAAAAAAAAAA A  A   AAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAYYAAAAAAAAAAAAAAA HA    AAAAAAAAAAAAAAAAA T A AAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD E VAAAAAAAAAAAAAA
    AAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAB AAAAAAAAAAAAA AAAAAAAA HAAAAAAAAAAALAAAAAAAAAAAAAAAAA
    AAAAAAAAAE E XAAAAAAAAAAAAAAAAAAAAAVJ   YAAAAAAAAAAAAAAAAAAAAPA  AAAAAAAAAAAAAA
    AAAAAAAA A E  AAAAAAAAAAAAAAAAAAAAAA     GKGAAAAAAAAAAAAABAAA UP  A AAAAAAAAAAA
    AAAAAACA AAAAAAAA BAAAAAAAAAAAA          A   AAAAAAAAAAY  AAAAA   AVPAAAAAAAAAA
    AAAAAAA AAAAAAAAAAAAYAAAAAAAA A               AAAAAA   AAAAAAAAAAA T AAAAAAAAAA
    AAAAA  AAAAAAAAAAAAAAAF    U   DAAA      GAA   AAAAAAAAAAAAAAAAAAAA AAAAAAAAAAA
    AAAAA  AAAAAAAAA C  ALCAAAAAAAAAAAAA Q  HAAAAAAAAGAWA     X AAAAAAAB AAAAAAAAAA
    AAAAAA AAABAAAAAAA       A AJZAAAAG AAAAA AAAA AA   G AA PMAAAAAAAAA AAAAAAAAAA
    AAAAAAA AAAAAAAAAGAAABEA   C  AA      A            OHAAV  AAAAAAAAAA AAAAAAAAAA
    AAAAAAA  AAAAAAAAAAADQRPAA A                C      A PAAAAAAAAAAAAAEDAAAAAAAAAA
    AAAAAAAAL  AWAAAAAAAAAAA  ADAISARSSRRQAHAAAAAAVO G MAAAAAEEAAAAAAAA  AAAAAAAAAA
    AAAAAAAAAAAATH AAAAAKAAAAAATCJALA      G    VJ AEAAAAAAAAAAAAA AA    AAAAAAAAAA
    AAAAAAAAAAAAA   CAAAAAAAANABAAAAAAAAAAAAEAACAAAAAAAAAAATNAAAD AAAAQAAAAAAAAAAAA
    AAAAAAAAAAAAAEA A  WBAAAJAAA AAAAAAAAAAAAAAAAAASI AAAM AAAAA UAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAZPALQ   AAAAVAA        AE H B   AAJAZLAAAA  ANAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAO MAIOJ Y AAAAZ AAAZ  C    A AAAPAAAA   M AAACAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAA   BEQK O  AAAAAAAAAAAAAAAAAAABVPKA  F  AAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAH WEZ  AEV X            T    R      Z AAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAA   A   AAJBR A    A    A C PAA   AZ LAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAA    J  AAAA A    AA   A AAAA F A GPAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAA    C  AAAAAA OAAAAA AAAAA Z A  PAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAA   AH  AAAAAAAAAAAAAAAAA K T JAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAE   AA  CAAAAAAAAAAAAAA AZG AANAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAA     A    AAABOSX    IWY FALAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAA     A        TBA   A RZ AAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAA         ZJHGEAGA     OAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAA     OAAAAAN       AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA""")